"""Entity extraction from insurance PDF text.

Two modes:
  * ``extract_entities_heuristic`` — deterministic parser for the synthetic
    documents generated by ``scripts/data_pipeline.py`` (stable entity ids are
    printed in the PDFs). This is the default and makes CDC fully testable.
  * LLM mode (Ollama) — same JSON contract, used when ``EXTRACTION_MODE`` is
    ``llm`` or (``auto``) when Ollama is reachable.

Both return::

    {"doc_id": "POL-0001", "mode": "heuristic"|"llm",
     "entities": {"Policy": {"POL-0001": {...props...}}, ...}}

Join fields (``policy_id``, ``claim_id``, ``investigator_id``,
``policyholder_id``) are included in props so the graph updater can derive edges.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import httpx

from graphrag.config import settings

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROMPT_FILE = PROJECT_ROOT / "prompts" / "extraction_prompts.txt"

SECTIONS = {"Policyholder", "Coverages", "Endorsements", "Fraud Flag", "Investigator"}

_KEYS = sorted(
    {
        # policy document
        "Policy ID", "Policy Number", "Type", "Term", "Status",
        "Annual Premium", "Deductible", "Policyholder ID", "Name",
        "Date of Birth", "Address", "Phone", "Email", "Risk Score",
        # claim document
        "Claim ID", "Claim Number", "Policy", "Date of Loss", "Amount", "Cause",
        # fraud flag + investigator sections
        "Flag ID", "Reason", "Confidence", "Severity", "Created By",
        "Investigator ID", "Role",
        # endorsement document
        "Endorsement ID", "Endorsement Number", "Effective Date", "Premium Adjustment",
    },
    key=len,
    reverse=True,
)

# \s* between cells: pdfplumber occasionally glues adjacent cells when a
# column is too narrow for its text (e.g. "ERRORS_OMISSIONS$3,000,000").
_COVERAGE_ROW = re.compile(
    r"^(COV-\d+)\s*([A-Z]+-[A-Z])\s*"
    r"(LIABILITY|PROPERTY|AUTO|EMPLOYEE_INJURY|ERRORS_OMISSIONS)\s*"
    r"(\$[\d,]+)\s*(\$[\d,]+)\s*(.*)$"
)
_ENDORSEMENT_ROW = re.compile(r"^(END-\d+)\s*(\S+)\s*([A-Z_]+)\s*(\d{4}-\d{2}-\d{2})\s*(-?\$?-?\d[\d,]*)$")
_TERM = re.compile(r"^(\d{4}-\d{2}-\d{2})\s+to\s+(\d{4}-\d{2}-\d{2})$")


# ---------------------------------------------------------------------------
# value normalization
# ---------------------------------------------------------------------------

def _to_native(value: str):
    """Convert money/numbers to float; keep everything else as a string."""
    s = value.strip()
    compact = s.replace("$", "").replace(",", "")
    if re.fullmatch(r"-?\d+(\.\d+)?", compact):
        return float(compact)
    return s


def _split_list(value: str) -> list[str]:
    return [item.strip() for item in value.split(";") if item.strip()]


# ---------------------------------------------------------------------------
# deterministic parser
# ---------------------------------------------------------------------------

def _detect_type(lines: list[str]) -> str | None:
    head = " ".join(lines[:3])
    if "Commercial Insurance Policy" in head:
        return "policy"
    if "Claim Report" in head:
        return "claim"
    if "Policy Endorsement" in head:
        return "endorsement"
    return None


def _match_key(line: str) -> str | None:
    for key in _KEYS:
        if line == key or line.startswith(key + " "):
            return key
    return None


def _parse(text: str) -> tuple[str | None, dict, list[dict], list[dict], str]:
    lines = [ln.strip() for ln in text.splitlines() if ln.strip()]
    doc_type = _detect_type(lines)

    kv: dict[str, str] = {}
    coverage_rows: list[dict] = []
    endorsement_rows: list[dict] = []
    description_parts: list[str] = []

    for ln in lines:
        if ln in SECTIONS:
            continue
        if match := _COVERAGE_ROW.match(ln):
            coverage_rows.append(
                {
                    "id": match.group(1),
                    "code": match.group(2),
                    "category": match.group(3),
                    "limit": _to_native(match.group(4)),
                    "deductible": _to_native(match.group(5)),
                    "exclusions": _split_list(match.group(6)),
                }
            )
            continue
        if match := _ENDORSEMENT_ROW.match(ln):
            endorsement_rows.append(
                {
                    "id": match.group(1),
                    "endorsement_number": match.group(2),
                    "type": match.group(3),
                    "effective_date": match.group(4),
                    "premium_adjustment": _to_native(match.group(5)),
                }
            )
            continue
        key = _match_key(ln)
        if key:
            kv[key] = ln[len(key):].strip()
            continue
        if doc_type == "claim" and "Cause" in kv:
            description_parts.append(ln)

    return doc_type, kv, coverage_rows, endorsement_rows, " ".join(description_parts)


def _build_policy(doc_id: str, kv: dict, coverages: list[dict], endorsements: list[dict]) -> dict:
    term = _TERM.match(kv.get("Term", ""))
    entities: dict[str, dict] = {}
    entities["Policyholder"] = {
        kv["Policyholder ID"]: {
            "id": kv["Policyholder ID"],
            "name": kv.get("Name"),
            "dob": kv.get("Date of Birth"),
            "address": kv.get("Address"),
            "phone": kv.get("Phone"),
            "email": kv.get("Email"),
            "risk_score": _to_native(kv.get("Risk Score", "")),
        }
    }
    entities["Policy"] = {
        doc_id: {
            "id": doc_id,
            "policy_number": kv.get("Policy Number"),
            "type": kv.get("Type"),
            "start_date": term.group(1) if term else None,
            "end_date": term.group(2) if term else None,
            "premium": _to_native(kv.get("Annual Premium", "")),
            "deductible": _to_native(kv.get("Deductible", "")),
            "status": kv.get("Status"),
            "policyholder_id": kv.get("Policyholder ID"),
        }
    }
    # policy_id is injected (like endorsements) so the CDC updater can derive
    # the COVERS edge for added/re-added coverages — not just the seeder.
    entities["Coverage"] = {
        c["id"]: {"id": c["id"], "policy_id": doc_id, **{k: v for k, v in c.items() if k != "id"}}
        for c in coverages
    }
    entities["Endorsement"] = {
        e["id"]: {"id": e["id"], "policy_id": doc_id, **{k: v for k, v in e.items() if k != "id"}}
        for e in endorsements
    }
    return {label: {eid: p for eid, p in ents.items() if p.get("id")} for label, ents in entities.items()}


def _build_claim(doc_id: str, kv: dict, description: str) -> dict:
    entities: dict[str, dict] = {}
    claim = {
        "id": doc_id,
        "claim_number": kv.get("Claim Number"),
        "policy_id": kv.get("Policy ID"),
        "date": kv.get("Date of Loss"),
        "amount": _to_native(kv.get("Amount", "")),
        "status": kv.get("Status"),
        "cause": kv.get("Cause"),
        "description": description,
    }
    entities["Claim"] = {doc_id: claim}
    if kv.get("Flag ID"):
        # claim_id is injected (like policy_id on coverages) so the CDC updater
        # can derive the FRAUD_DETECTED edge for added/re-added fraud flags.
        entities["FraudFlag"] = {
            kv["Flag ID"]: {
                "id": kv["Flag ID"],
                "claim_id": doc_id,
                "reason": kv.get("Reason"),
                "confidence": _to_native(kv.get("Confidence", "")),
                "severity": kv.get("Severity"),
                "created_by": kv.get("Created By"),
            }
        }
    if kv.get("Investigator ID"):
        entities["Investigator"] = {
            kv["Investigator ID"]: {
                "id": kv["Investigator ID"],
                "name": kv.get("Name"),
                "role": kv.get("Role"),
                "email": kv.get("Email"),
            }
        }
        claim["investigator_id"] = kv["Investigator ID"]
    return entities


def _build_endorsement(doc_id: str, kv: dict) -> dict:
    return {
        "Endorsement": {
            doc_id: {
                "id": doc_id,
                "endorsement_number": kv.get("Endorsement Number"),
                "policy_id": kv.get("Policy"),
                "type": kv.get("Type"),
                "effective_date": kv.get("Effective Date"),
                "premium_adjustment": _to_native(kv.get("Premium Adjustment", "")),
            }
        }
    }


def _hint_id(hint: str | None) -> str | None:
    if not hint:
        return None
    match = re.search(r"([A-Z]{2,6}-\d{3,})", hint)
    return match.group(1) if match else None


def extract_entities_heuristic(text: str, doc_id_hint: str | None = None) -> dict:
    """Deterministic extraction for the synthetic insurance PDFs."""
    doc_type, kv, coverages, endorsements, description = _parse(text)

    builders = {
        "policy": lambda: _build_policy(doc_id, kv, coverages, endorsements),
        "claim": lambda: _build_claim(doc_id, kv, description),
        "endorsement": lambda: _build_endorsement(doc_id, kv),
    }
    if doc_type not in builders:
        return {"doc_id": _hint_id(doc_id_hint) or (doc_id_hint or ""), "entities": {}, "mode": "heuristic"}

    key = {"policy": "Policy ID", "claim": "Claim ID", "endorsement": "Endorsement ID"}[doc_type]
    doc_id = kv.get(key) or _hint_id(doc_id_hint) or ""
    entities = builders[doc_type]()
    # drop None/empty props and the placeholder flag
    for label, ents in entities.items():
        entities[label] = {
            eid: {k: v for k, v in props.items() if v not in (None, "", [])}
            for eid, props in ents.items()
        }
    entities = {label: ents for label, ents in entities.items() if ents}
    return {"doc_id": doc_id, "entities": entities, "mode": "heuristic"}


# ---------------------------------------------------------------------------
# LLM path — v2 multi-provider layer (OpenAI-compatible → Ollama → heuristic)
# ---------------------------------------------------------------------------

def _ollama_available() -> bool:
    try:
        return httpx.get(f"{settings.LLAMA_API_URL}/api/tags", timeout=2).status_code == 200
    except Exception:
        return False


def _load_prompts() -> tuple[str, str]:
    return PROMPT_FILE.read_text(encoding="utf-8").split("\n---\n", 1)


def _render_extraction_prompt(text: str) -> str:
    """Fill the extraction template — brace-safe (document text may hold {}).

    A document containing literal braces (JSON snippets in clauses, etc.)
    must not crash ``.format()``; the swap goes through a sentinel.
    """
    prompt, _qa = _load_prompts()
    return prompt.replace("{text}", "\x00DOC_TEXT\x00").replace("\x00DOC_TEXT\x00", text)


def _extract_with_llm(text: str, doc_id_hint: str | None) -> dict:
    """Ollama /api/generate extraction (v1 contract: format=json)."""
    prompt = _render_extraction_prompt(text)
    response = httpx.post(
        f"{settings.LLAMA_API_URL}/api/generate",
        json={"model": settings.LLAMA_MODEL, "prompt": prompt,
              "stream": False, "format": "json"},
        timeout=120,
    )
    response.raise_for_status()
    entities = json.loads(response.json()["response"])
    doc_id = _hint_id(doc_id_hint) or ""
    for label, ents in entities.items():
        for eid, props in ents.items():
            if not doc_id and re.fullmatch(r"(POL|CLM|END)-\d+", eid):
                doc_id = eid
    return {"doc_id": doc_id, "entities": entities, "mode": "llm"}


def _extract_with_openai(text: str, doc_id_hint: str | None) -> dict:
    """OpenAI-compatible Chat Completions extraction (structured JSON)."""
    from graphrag.llm.openai_compat import OpenAICompatProvider

    prompt = _render_extraction_prompt(text)
    result = OpenAICompatProvider().generate(
        prompt,
        model=settings.LLAMA_MODEL if settings.LLM_PROVIDER == "ollama"
        else (settings.OPENAI_MODEL),
        max_tokens=2048,
        temperature=0.0,
        json_mode=True,
    )
    # tolerate markdown fences some gateways wrap JSON in
    raw = result.text.strip()
    if raw.startswith("```"):
        raw = raw.strip("`")
        raw = raw.removeprefix("json")
    entities = json.loads(raw)
    doc_id = _hint_id(doc_id_hint) or ""
    for label, ents in entities.items():
        for eid, props in ents.items():
            if not doc_id and re.fullmatch(r"(POL|CLM|END)-\d+", eid):
                doc_id = eid
    return {"doc_id": doc_id, "entities": entities, "mode": "llm",
            "provider": result.provider, "model": result.model}


def _openai_extraction_path() -> bool:
    """Prefer the OpenAI-compatible provider for extraction (like answers)."""
    if settings.LLM_PROVIDER == "openai":
        return True
    if settings.LLM_PROVIDER == "auto" and settings.OPENAI_BASE_URL:
        from graphrag.llm.factory import get_provider
        provider = get_provider("auto")
        return provider is not None and provider.name == "openai"
    return False


def extract_entities(text: str, doc_id_hint: str | None = None, mode: str | None = None) -> dict:
    """Extract entities — LLM when requested/available, heuristic otherwise.

    Provider chain (v2): OpenAI-compatible when configured → Ollama →
    deterministic heuristic. ``mode="llm"`` requires a provider; ``auto``
    degrades gracefully on any failure.
    """
    mode = mode or settings.EXTRACTION_MODE
    if mode in ("llm", "auto"):
        if _openai_extraction_path():
            try:
                return _extract_with_openai(text, doc_id_hint)
            except Exception:
                if mode == "llm":
                    raise
                # auto: fall through to the Ollama attempt below
        if mode in ("llm", "auto") and _ollama_available():
            try:
                return _extract_with_llm(text, doc_id_hint)
            except Exception:
                if mode == "llm":
                    raise
        if mode == "llm" and not _openai_extraction_path() and not _ollama_available():
            raise RuntimeError(
                f"extraction mode 'llm' requires a provider (Ollama at "
                f"{settings.LLAMA_API_URL} or OPENAI_BASE_URL)"
            )
    return extract_entities_heuristic(text, doc_id_hint)
